apiVersion: "v1"
name: loki
version: 1.0.0
appVersion: v1.0.0
kubeVersion: "^1.10.0-0"
description: "A custom Helm chart based on Grafana version 2.10.2"
home: https://grafana.com/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
sources:
  - https://github.com/grafana/loki
maintainers:
  - name: albert
    email: albert@wemeetmobility.com
