apiVersion: v1
appVersion: v1.0.0.
description: 'Customized New Cart based on the Loki Helm chart version 2.16.0'
home: https://grafana.com/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
kubeVersion: ^1.10.0-0
maintainers:
- email: albert@wemeetmobility.com
  name: albert
name: loki
sources:
- https://github.com/grafana/loki
version: 1.0.0
